jobs:
  - job: 'Windows'
    strategy:
      matrix:
        Python34:
          python.version: '3.4'
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
    pool:
      vmImage: 'vs2017-win2016'
    timeoutInMinutes: 360
    steps:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH
      - script: conda create --yes --quiet --name test-environment
        displayName: Create Anaconda environment
      - script: |
          call activate test-environment
          conda install --yes --quiet -c conda-forge pandoc pip
        displayName: Install Anaconda packages
      - script: |
          call activate test-environment
          pip install -v .[test]
          pytest -v
        displayName: Build and run tests
